# Generated by Django 5.0.6 on 2024-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
